# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/luminoso/UA-work/CR/IP
  /home/luminoso/UA-work/CR/projectofinal
} [current_project]
set_property ip_output_repo /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/luminoso/UA-work/CR/projectofinal/8ones.coe
read_verilog -library xil_defaultlib /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_Unroll_ROM_last_0_0/src/Nexys4_Master.xdc]
set_property used_in_implementation false [get_files -all /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_Count_Ones_0_0/constrs_1/imports/CR/master.xdc]
set_property used_in_implementation false [get_files -all /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/constrs_1/imports/CR/master.xdc
set_property used_in_implementation false [get_files /home/luminoso/UA-work/CR/projectofinal/FSM_tester/project_1/project_1.srcs/constrs_1/imports/CR/master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
