# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/luminoso/UA-work/CR/projectofinal/FSMCountOnes/FSMCountOnes.cache/wt [current_project]
set_property parent.project_path /home/luminoso/UA-work/CR/projectofinal/FSMCountOnes/FSMCountOnes.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/luminoso/UA-work/CR/projectofinal/FSMCountOnes/FSMCountOnes.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/luminoso/UA-work/CR/projectofinal/FSMCountOnes/FSMCountOnes.srcs/sources_1/new/CountOnes.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/luminoso/UA-work/CR/projectofinal/FSMCountOnes/FSMCountOnes.srcs/constrs_1/imports/CR/master.xdc
set_property used_in_implementation false [get_files /home/luminoso/UA-work/CR/projectofinal/FSMCountOnes/FSMCountOnes.srcs/constrs_1/imports/CR/master.xdc]


synth_design -top Count_Ones -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Count_Ones.dcp

catch { report_utilization -file Count_Ones_utilization_synth.rpt -pb Count_Ones_utilization_synth.pb }
